version: '3.2'

services:
        db:
                image: postgres
                ports: 
                        - 5432:5432
                environment:
                        - POSTGRES_USER=crm
                        - POSTGRESS_PASSWORD=crm
                        - POSTGRES_DB=crm
